/* THOR: guided arena client. All scoring, permissions and timing are server-authoritative. */
(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const escape = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const timeValue = (value) => typeof value === 'number' ? value : Date.parse(value || '') || 0;
  const roles = {attack:'Atacante',defense:'Defensor'};
  const stages = ['Conexão aberta','Alvo reconhecido','Pista encontrada','Acesso obtido'];
  const phases = ['lobby','preparing','running','finished'];
  const phaseText = {
    lobby:['Entrada dos participantes','O professor organiza os times. Escolham pelo menos um atacante e um defensor por equipe.'],
    preparing:['Preparação em andamento','Os times estudam as ferramentas e ensaiam os comandos enquanto o professor prepara os PDFs.'],
    running:['Operação em andamento','Investigue os adversários e responda a cada conexão de ataque. O tempo restante é compartilhado por todos.'],
    finished:['Operação encerrada','O tempo terminou. Confira as capturas, as defesas e o bônus de proteção no ranking final.']
  };
  const tools = [
    {id:'scan',kind:'attack',name:'Reconhecer alvo',description:'Localiza o cofre virtual da equipe adversária.',hint:'É o primeiro passo de uma conexão nova. Se o defensor desviar a conexão, use scan novamente.',effect:'Avança do estágio 0 para 1: alvo reconhecido.',concept:'Serviços e endereçamento de rede.',cooldown:'4 s entre comandos de ataque'},
    {id:'inspect',kind:'attack',name:'Inspecionar permissões',description:'Investiga uma configuração de acesso deixada no cofre.',hint:'Execute depois de scan. Procure a pista de permissão no resultado.',effect:'Avança do estágio 1 para 2: pista encontrada.',concept:'Permissões e exposição de arquivos.',cooldown:'4 s entre comandos de ataque'},
    {id:'access',kind:'attack',name:'Obter acesso',description:'Usa a pista preparada no desafio para abrir uma sessão.',hint:'Execute depois de inspect. O defensor poderá revogar esta sessão.',effect:'Avança do estágio 2 para 3: acesso obtido.',concept:'Autenticação e controle de sessão.',cooldown:'4 s entre comandos de ataque'},
    {id:'extract',kind:'attack',name:'Extrair documento',description:'Recupera o PDF da equipe adversária e registra uma captura.',hint:'Você precisa ter acesso obtido. Cada time captura cada adversário uma única vez.',effect:'Baixa o PDF e concede 50 pontos para seu time.',concept:'Acesso a arquivos e rastros de leitura.',cooldown:'4 s entre comandos de ataque'},
    {id:'reconnect',kind:'attack',name:'Reconectar',description:'Abre novamente uma conexão que foi bloqueada.',hint:'Use quando o defensor bloquear sua conexão. Depois, retome com scan.',effect:'Remove o bloqueio e reinicia sua investigação no estágio 0.',concept:'Conexões e políticas de bloqueio.',cooldown:'4 s entre comandos de ataque'},
    {id:'reroute',kind:'defense',name:'Desviar conexão',description:'Muda o IP virtual visto pelo atacante selecionado.',hint:'Use somente na etapa Alvo reconhecido. As outras conexões continuam de onde estavam.',effect:'Reinicia apenas essa conexão no estágio 0. Defesa válida: +5 pontos.',concept:'Rotas e endereçamento virtual.',cooldown:'5 s entre defesas do jogador'},
    {id:'block',kind:'defense',name:'Bloquear atacante',description:'Interrompe uma conexão de ataque específica.',hint:'Use somente na etapa Pista encontrada. O atacante precisa reconectar antes de avançar.',effect:'Bloqueia apenas o incidente escolhido. Defesa válida: +5 pontos.',concept:'Regras de firewall por conexão.',cooldown:'5 s entre defesas do jogador'},
    {id:'revoke',kind:'defense',name:'Revogar acesso',description:'Encerra o acesso obtido por um atacante.',hint:'Só funciona quando a conexão está em Acesso obtido, antes da extração.',effect:'Remove a sessão daquela conexão. Defesa válida: +5 pontos.',concept:'Privilégios e ciclo de vida de sessões.',cooldown:'5 s entre defesas do jogador'},
    {id:'logs',kind:'defense',name:'Consultar logs',description:'Mostra os registros recentes para orientar a equipe.',hint:'Use para entender quem está atacando e como a investigação está avançando.',effect:'Consulta informações. Não altera incidentes nem gera pontos.',concept:'Observabilidade e registros do sistema.',cooldown:'Consulta sem pontuação'}
  ];
  const toolById = Object.fromEntries(tools.map((tool) => [tool.id,tool]));
  const state = {code:'',token:'',snapshot:null,tab:'operation',public:false,busy:false,pollTimer:null,polling:false,toastTimer:null,serverOffset:0,lastServerAt:0,connected:true,attackCommand:'',defenseCommand:'',entryMode:{attack:null,defense:null},training:{stage:0,status:'active',route:1},selectedMembers:new Set(),renderCache:new Map(),dismissedAlerts:new Set(),queuedAlerts:new Set(),alertQueue:[],alertsInitialized:false,reducedEffects:false};
  let sessionGeneration = 0;

  function setText(id,text) { const element=$(id); if(element && element.textContent!==String(text??'')) element.textContent=text??''; }
  function setHtml(id,html) { if(state.renderCache.get(id)===html) return; const element=$(id); if(element) {element.innerHTML=html;state.renderCache.set(id,html);} }
  function show(id,visible) { if($(id)) $(id).hidden=!visible; }
  function notify(message,error=false) { const element=$('toast'); element.textContent=message; element.classList.toggle('error',error); element.hidden=false;clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>element.hidden=true,error?7000:4200); }
  function terminal(id,text,kind='') {const node=document.createElement('div');node.className=`terminal-line ${kind}`;node.textContent=text;const box=$(id);box.appendChild(node);while(box.children.length>90)box.firstChild.remove();box.scrollTop=box.scrollHeight;}
  function localSession(code) {try{return JSON.parse(localStorage.getItem(`thor:session:${code}`)||'null');}catch{return null;}}
  function entryMode(mode) {show('entry-choice',!mode);show('create-form',mode==='teacher');show('join-form',mode==='student');if(mode==='teacher'){$('activity-title').focus();}else if(mode==='student'){($('join-code').value?$('join-name'):$('join-code')).focus();}const url=new URL(location.href);url.searchParams.delete('password');url.searchParams.delete('title');if(mode)url.searchParams.set('mode',mode);else url.searchParams.delete('mode');history.replaceState(null,'',url);}
  function saveSession(result) {try {localStorage.setItem(`thor:session:${result.code}`,JSON.stringify({code:result.code,token:result.token,viewer:result.viewer||result.snapshot?.viewer,participantId:result.participantId,name:$('join-name').value}));localStorage.setItem('thor:lastActivity',result.code);}catch{notify('Seu navegador não permite salvar a sessão. Mantenha esta aba aberta.',true);}}
  function updateSavedSession() {const code=$('join-code').value.trim().toUpperCase();const saved=localSession(code);show('saved-session',Boolean(saved?.token));if(saved?.token)setHtml('saved-session',`<p>Há uma sessão de ${saved.viewer?.kind==='teacher'?'professor':'participante'} salva neste navegador.</p><button class="text-button" type="button" data-resume="${escape(code)}">Retomar sessão →</button>`);}
  function updateTeacherSession(){let code='';try{code=localStorage.getItem('thor:lastActivity')||'';}catch{}const saved=localSession(code);const exists=saved?.viewer?.kind==='teacher'&&saved?.token;show('teacher-saved-session',Boolean(exists));if(exists)setHtml('teacher-saved-session',`<p>Você já abriu a atividade ${escape(code)} neste navegador.</p><button type="button" class="text-button" data-resume="${escape(code)}">Continuar minha atividade →</button>`);}
  function apiPath(suffix='') {return `/api/activities/${encodeURIComponent(state.code)}${suffix}`;}
  async function request(url,{method='GET',body,auth=true}={}) {
    const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);
    try {const headers={};if(body!==undefined)headers['Content-Type']='application/json';if(auth && state.token)headers.Authorization=`Bearer ${state.token}`;
      const response=await fetch(url,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal,cache:'no-store'});
      let data;try{data=await response.json();}catch{throw new Error('O servidor retornou uma resposta inesperada. Verifique se a arena está em execução.');}
      if(!response.ok){if(data.snapshot?.activity?.code===state.code)applySnapshot(data.snapshot);throw new Error(data.error||'Não foi possível concluir a solicitação.');}return data;
    }catch(error){if(error.name==='AbortError')throw new Error('O servidor demorou para responder. Tente novamente.');if(error instanceof TypeError)throw new Error('Não foi possível conectar à arena. Verifique sua conexão.');throw error;}finally{clearTimeout(timeout);}
  }
  function publicUrl() {const url=new URL(location.pathname,location.origin);url.searchParams.set('activity',state.code);url.searchParams.set('public','1');return url.toString();}
  function setConnected(connected) {state.connected=connected;show('connection-warning',!connected);$('connection-state').classList.toggle('disconnected',!connected);$('connection-state').innerHTML=`<span class="live-dot"></span> ${connected?'Conectado':'Reconectando'}`;}
  function applySnapshot(snapshot) {
    if(!snapshot?.activity)return;const serverAt=timeValue(snapshot.serverNow);
    if(serverAt && serverAt<state.lastServerAt)return;
    const previousStatus=state.snapshot?.activity.status;state.snapshot=snapshot;state.lastServerAt=serverAt;if(serverAt)state.serverOffset=serverAt-Date.now();setConnected(true);render();
    if(snapshot.activity.status==='finished' && previousStatus!=='finished'){switchTab('ranking');if(previousStatus)notify('Atividade encerrada. O ranking final já está disponível.');}
  }
  async function enterSession(code,token='',snapshot=null,isPublic=false) {
    sessionGeneration++;clearTimeout(state.pollTimer);state.renderCache.clear();state.code=code;state.token=isPublic?'':token;state.public=isPublic;state.snapshot=null;state.lastServerAt=0;state.tab=isPublic?'ranking':'operation';state.selectedMembers.clear();
    state.entryMode={attack:null,defense:null};$('attack-command').value='';$('defense-command').value='';state.alertQueue=[];state.queuedAlerts.clear();state.alertsInitialized=false;state.dismissedAlerts=new Set();try{state.dismissedAlerts=new Set(JSON.parse(localStorage.getItem(`thor:alerts:${code}`)||'[]'));state.reducedEffects=localStorage.getItem('thor:reducedEffects')==='1';}catch{}
    const url=new URL(location.href);url.search='';url.searchParams.set('activity',code);if(isPublic)url.searchParams.set('public','1');history.replaceState(null,'',url);
    if(snapshot)applySnapshot(snapshot);else applySnapshot(await request(apiPath()));
    show('entry-view',false);show('arena-view',true);document.body.classList.toggle('public-view',isPublic);switchTab(state.tab);schedulePoll();
  }
  function schedulePoll() {clearTimeout(state.pollTimer);if(state.code)state.pollTimer=setTimeout(poll,document.hidden?4000:2000);}
  async function poll() {
    if(!state.code||state.polling){schedulePoll();return;}state.polling=true;const generation=sessionGeneration;
    try{const snapshot=await request(apiPath());if(generation===sessionGeneration)applySnapshot(snapshot);}catch(error){if(generation===sessionGeneration)setConnected(false);}finally{state.polling=false;if(generation===sessionGeneration)schedulePoll();}
  }
  async function mutate(action,outputId) {
    if(state.busy)return null;state.busy=true;updateEnabled();
    try{const result=await request(apiPath('/action'),{method:'POST',body:action});applySnapshot(result.snapshot);if(result.message){if(outputId)terminal(outputId,result.message);else notify(result.message);}if(result.download)await downloadDocument(result.download,outputId);return result;
    }catch(error){if(outputId)terminal(outputId,error.message,'error');notify(error.message,true);return null;}finally{state.busy=false;updateEnabled();}
  }
  async function downloadDocument(download,outputId) {
    const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);
    try{const response=await fetch(apiPath(`/download/${encodeURIComponent(download.ticket)}`),{cache:'no-store',signal:controller.signal});if(!response.ok){let message='A captura foi registrada, mas o download não foi concluído.';try{message=(await response.json()).error||message;}catch{}throw new Error(message);}const blob=await response.blob();const objectUrl=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=objectUrl;anchor.download=download.name||'retrospectiva.pdf';anchor.hidden=true;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),60000);if(outputId)terminal(outputId,`PDF recuperado: ${download.name}. Captura registrada para sua equipe.`);notify('Documento capturado. O download do PDF foi iniciado.');}finally{clearTimeout(timeout);}
  }
  function switchTab(tab) {
    if(state.public)tab='ranking';if(tab==='toolkit' && state.snapshot?.activity.status==='lobby' && state.snapshot.viewer.kind!=='teacher'){notify('As ferramentas serão liberadas pelo professor na preparação.');return;}
    state.tab=tab;for(const name of ['operation','toolkit','ranking'])show(`${name}-panel`,name===tab);document.querySelectorAll('[data-tab]').forEach(button=>{const selected=button.dataset.tab===tab;button.classList.toggle('active',selected);button.setAttribute('aria-current',selected?'page':'false');});
  }
  function teamMembers(team) {return (state.snapshot?.participants||[]).filter(participant=>participant.teamId===team.id || team.memberIds?.includes(participant.id));}
  function teamReady(team) {const members=teamMembers(team);return members.length>=2&&members.every(member=>Boolean(member.role))&&members.some(member=>member.role==='attack')&&members.some(member=>member.role==='defense');}
  function render() {
    const snapshot=state.snapshot;const {activity,viewer}=snapshot;const isTeacher=viewer.kind==='teacher';const isStudent=viewer.kind==='student';const isPublic=viewer.kind==='public'||state.public;
    setText('activity-name',activity.title);setText('activity-code-label',`ATIVIDADE ${activity.code}`);setText('viewer-badge',isTeacher?'PROFESSOR':isPublic?'TELA PÚBLICA':roles[viewer.role]?.toUpperCase()||'PARTICIPANTE');setText('phase-title',(phaseText[activity.status]||phaseText.lobby)[0]);setText('phase-description',(phaseText[activity.status]||phaseText.lobby)[1]);
    show('teacher-area',isTeacher);show('student-area',isStudent);show('arena-tabs',!isPublic);
    const latest=(snapshot.announcements||[]).slice().sort((a,b)=>timeValue(b.at)-timeValue(a.at))[0];show('alert-section',Boolean(latest));if(latest){setText('latest-alert',latest.text);setText('alert-time',formatTime(latest.at));}
    renderEvents('announcement-list',snapshot.announcements||[],'Nenhum aviso transmitido ainda.');renderRanking();renderBroadcast();renderEffect();
    if(isTeacher)renderTeacher();if(isStudent)renderStudent();if(isPublic)switchTab('ranking');updateClock();updateEnabled();
  }
  function formatTime(value) {const timestamp=timeValue(value);return timestamp?new Date(timestamp).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'--:--';}
  function renderBroadcast() {
    if(state.snapshot.viewer.kind!=='student'||state.snapshot.activity.status==='finished'){state.alertQueue=[];if($('player-alert').open)$('player-alert').close();return;}
    let fresh=(state.snapshot.announcements||[]).filter(item=>!state.dismissedAlerts.has(item.id)&&!state.queuedAlerts.has(item.id));
    if(!state.alertsInitialized){for(const item of fresh.slice(0,-1))state.dismissedAlerts.add(item.id);fresh=fresh.slice(-1);state.alertsInitialized=true;}
    for(const item of fresh){state.queuedAlerts.add(item.id);state.alertQueue.push(item);}
    if(state.alertQueue.length&&!$('player-alert').open){setText('player-alert-message',state.alertQueue[0].text);$('player-alert').showModal();$('dismiss-player-alert').focus();}
  }
  function dismissBroadcast() {
    if($('player-alert').open)$('player-alert').close();
    const item=state.alertQueue.shift();if(item){state.dismissedAlerts.add(item.id);try{localStorage.setItem(`thor:alerts:${state.code}`,JSON.stringify([...state.dismissedAlerts].slice(-60)));}catch{}}
    if(state.snapshot)renderBroadcast();
  }
  function renderEffect() {
    const now=Date.now()+state.serverOffset;
    const active=state.snapshot?.viewer.kind==='student'&&state.snapshot.activity.status==='running'?(state.snapshot.effects||[]).find(item=>item.endsAt>now):null;
    const effect=active&&(state.snapshot.effectCatalog||[]).find(item=>item.id===active.effectId);
    const reduced=state.reducedEffects||matchMedia('(prefers-reduced-motion: reduce)').matches;
    document.body.dataset.effect=effect&&!reduced?effect.id:'';show('effect-hud',Boolean(effect));show('effect-decoration',Boolean(effect&&!reduced&&['matrix','retro','glitch'].includes(effect.id)));
    if(effect)setText('effect-label',`${effect.name} · ${Math.max(0,Math.ceil((active.endsAt-now)/1000))}s${reduced?' · efeito reduzido':''}`);
    $('reduce-effect').hidden=reduced;
  }
  function renderTeamMetrics() {
    const {teams=[],teamMetrics=[],incidents=[],activity}=state.snapshot;
    setHtml('team-metrics-summary',teams.map(team=>`<button type="button" class="metrics-team-card ${team.leakCount?'has-leak':''}" data-metrics="${escape(team.id)}"><strong>${escape(team.name)}</strong><span>${team.score} pontos · ${team.captureCount} capturas · ${team.defenseCount} defesas</span><b>${team.leakCount||0} vazamento${team.leakCount===1?'':'s'}</b></button>`).join('')||'<p class="empty-state">As métricas aparecem após formar os times.</p>');
    updateOptions('metrics-team',teams.map(team=>({value:team.id,label:team.name})),'Selecione um grupo');
    const team=teams.find(item=>item.id===$('metrics-team').value);const detail=teamMetrics.find(item=>item.teamId===team?.id);
    if(!team||!detail){setHtml('team-metrics-detail','');return;}
    const stat=(value,label)=>`<div><strong>${Number(value)||0}</strong><span>${label}</span></div>`;
    const breakdown=(values)=>Object.entries(values||{}).map(([command,count])=>`${escape(command)}: ${Number(count)||0}`).join(' · ')||'—';
    const history=(items,empty)=>items.length?items.slice().reverse().map(item=>`<li><time>${escape(formatTime(item.at))}</time> ${escape(item.teamName)}</li>`).join(''):`<li class="muted">${empty}</li>`;
    const connections=incidents.filter(item=>['active','blocked'].includes(item.status)&&(item.attackerTeamId===team.id||item.defenderTeamId===team.id));
    setHtml('team-metrics-detail',`<h3 class="metrics-title">${escape(team.name)}</h3><div class="metrics-grid">${stat(team.score,'Pontos')}${stat(team.leakCount,'Documento vazado')}${stat(team.captureCount,'Capturas únicas')}${stat(team.defenseCount,'Defesas válidas')}${stat(detail.outgoing,'Ataques abertos')}${stat(detail.incoming,'Conexões recebidas')}${stat(detail.attackCommands,'Comandos de ataque')}${stat(detail.rejectedCommands,'Comandos rejeitados')}</div><p class="metrics-points">Reserva de defesa: ${team.defenseReserve?.charges ?? 0}/${team.defenseReserve?.capacity ?? 2} · recarga a cada 8 s.</p><p class="metrics-points">Pontuação: ${detail.points.captures} em capturas + ${detail.points.defenses} em defesas + ${detail.points.survival} de proteção.</p><div class="table-scroll"><table class="member-metrics"><caption>Atividade por integrante</caption><thead><tr><th>Integrante</th><th>Função</th><th>Ataques</th><th>Defesas*</th><th>Capturas</th><th>Rejeitados*</th><th>Comandos*</th></tr></thead><tbody>${detail.members.map(member=>`<tr><th>${escape(member.name)}<small>${member.online?'Conectado':'Sem atualização recente'}${member.lockUntil>Date.now()+state.serverOffset?' · proteção de autoclique ativa':''}</small></th><td>${escape(roles[member.role]||'Escolhendo')}</td><td>${member.attackCommands||0}</td><td>${member.defenseCommands||0}</td><td>${member.captures||0}</td><td>${member.rejectedCommands||0}</td><td>${breakdown(member.attackByCommand)}<br>${breakdown(member.defenseByCommand)}</td></tr>`).join('')}</tbody></table></div><p class="muted small-text">* Detalhamento por comando, defesas por integrante e rejeições desde ${escape(formatTime(activity.metricsStartedAt))}. Pontos, capturas, defesas do grupo e vazamentos incluem todo o histórico da atividade.</p><div class="metrics-history"><div><h4>Quem capturou este PDF · ${team.leakCount||0}</h4><ul>${history(detail.leaks,'Nenhum vazamento registrado.')}</ul></div><div><h4>PDFs capturados pelo grupo · ${team.captureCount}</h4><ul>${history(detail.capturedTeams,'Nenhuma captura registrada.')}</ul></div></div><h4>Conexões em andamento</h4><div class="connection-list">${connections.map(item=>`<div class="incident-row"><span class="incident-detail"><strong>${escape(item.attackerTeamName)} → ${escape(item.defenderTeamName)}</strong><small>${escape(item.attackerName)} · ${escape(stages[item.stage])} · ${item.defenseCount} respostas</small></span><span class="incident-status">${item.status==='blocked'?'BLOQUEADO':'ATIVO'}</span></div>`).join('')||'<p class="muted small-text">Nenhuma conexão em andamento.</p>'}</div>`);
  }
  function renderEffectControls() {
    const {teams=[],effectCatalog=[],effects=[]}=state.snapshot;
    updateOptions('effect-team',teams.map(team=>({value:team.id,label:team.name})),'Escolha um grupo');updateOptions('effect-kind',effectCatalog.map(item=>({value:item.id,label:item.name})),'Escolha um efeito');
    const effect=effectCatalog.find(item=>item.id===$('effect-kind').value);setText('effect-description',effect?.description||'');
    const active=effects.find(item=>item.teamId===$('effect-team').value&&item.endsAt>Date.now()+state.serverOffset);
    setText('effect-status',state.snapshot.activity.status!=='running'?'Disponível durante a rodada.':active?`Efeito em andamento: ${effectCatalog.find(e=>e.id===active.effectId)?.name||''}.`:'Grupo pronto para receber um efeito.');
    $('effect-form').querySelector('button').disabled=state.busy||state.snapshot.activity.status!=='running'||Boolean(active)||!$('effect-team').value;$('clear-effect').disabled=state.busy||!active;
  }
  function renderEvents(id,events,empty='Nenhuma ação registrada ainda.') {setHtml(id,events.length?events.slice().sort((a,b)=>timeValue(b.at)-timeValue(a.at)).slice(0,40).map(event=>`<div class="event-row"><time>${escape(formatTime(event.at))}</time><p>${escape(event.text)}</p></div>`).join(''):`<div class="empty-state">${escape(empty)}</div>`);}
  function renderRanking() {
    const {activity,ranking=[],viewer}=state.snapshot;const finished=activity.status==='finished';setText('ranking-title',finished?'Ranking final':'Ranking ao vivo');setText('ranking-description',finished?'Capturas e defesas somadas. Equipes sem documento extraído receberam 50 pontos de proteção.':'O bônus de proteção será aplicado somente quando a atividade terminar.');
    setHtml('ranking-list',ranking.length?ranking.map((team,index)=>`<article class="ranking-row ${index===0?'first':''}"><span class="ranking-position">${escape(team.position??index+1)}</span><div class="ranking-name"><h3>${escape(team.name)}${team.id===viewer.teamId?' <span class="chip subtle">SEU TIME</span>':''}</h3><p>${finished?(team.survivalBonus?'COFRE PROTEGIDO · BÔNUS +50':'DOCUMENTO CAPTURADO'):'OPERAÇÃO EM ANDAMENTO'}</p></div><div class="ranking-details"><div><strong>${Number(team.captureCount)||0}</strong><span>CAPTURAS</span></div><div><strong>${Number(team.defenseCount)||0}</strong><span>DEFESAS</span></div><div><strong>${Number(team.leakCount)||0}</strong><span>VAZAMENTOS</span></div><div><strong>${Number(team.survivalBonus)||0}</strong><span>BÔNUS</span></div></div><div class="ranking-score"><strong>${Number(team.score)||0}</strong><span>PONTOS</span></div></article>`).join(''):'<div class="empty-state">O ranking aparecerá assim que os times forem criados.</div>');
  }
  function renderTeacher() {
    const {activity,participants=[],teams=[],events=[]}=state.snapshot;const editable=['lobby','preparing'].includes(activity.status);setText('participant-count',participants.length);setText('team-count',teams.length);setText('copy-code',activity.code);$('public-link').href=publicUrl();
    for(const id of [...state.selectedMembers])if(!participants.some(participant=>participant.id===id&&!participant.teamId))state.selectedMembers.delete(id);
    const roster=participants.map(participant=>{const team=teams.find(item=>item.id===participant.teamId);return `<label class="participant-item"><input type="checkbox" data-member="${escape(participant.id)}" ${state.selectedMembers.has(participant.id)?'checked':''} ${!editable||participant.teamId?'disabled':''}><span class="participant-name">${escape(participant.name)}<small>${team?escape(team.name):'Aguardando time'}</small></span><span class="presence ${participant.online?'':'offline'}" title="${participant.online?'Conectado recentemente':'Sem atualização recente'}"></span></label>`;}).join('');
    setHtml('participant-list',roster||'<div class="empty-state">Compartilhe o código acima. Os participantes aparecerão aqui conforme entrarem.</div>');setText('selected-count',`(${state.selectedMembers.size})`);
    setHtml('team-list',teams.length?teams.map(team=>{const members=teamMembers(team);const ready=teamReady(team);return `<article class="team-row"><div class="team-row-info"><h3>${escape(team.name)} <span class="leak-counter ${team.leakCount?'has-leak':''}">${team.leakCount||0} vazamentos</span></h3><button type="button" class="text-button metrics-link" data-metrics="${escape(team.id)}">Ver métricas ↗</button><p>${members.map(member=>`${escape(member.name)} · ${escape(roles[member.role]||'sem função')}`).join(' / ')}</p><p class="team-role-state ${ready?'ready':''}">${ready?'✓ Todas as funções definidas, com atacante e defensor':'◌ Aguardando funções: precisa de atacante e defensor'}</p></div><div class="document-box"><span class="document-state ${team.document?.ready?'ready':''}">${team.document?.ready?'✓ PDF preparado':'◌ Aguardando PDF'}</span><span class="document-name" title="${escape(team.document?.name||'')}">${escape(team.document?.name||'Um documento por time')}</span>${editable?`<label class="upload-label">${team.document?.ready?'Trocar PDF':'Enviar PDF'} ↥<input data-upload="${escape(team.id)}" type="file" accept="application/pdf,.pdf" aria-label="Enviar PDF de ${escape(team.name)}"></label>`:''}</div>${editable?`<button class="team-delete" data-delete-team="${escape(team.id)}" type="button" aria-label="Desfazer time ${escape(team.name)}" title="Desfazer time">×</button>`:''}</article>`;}).join(''):'<div class="empty-state">Crie o primeiro time selecionando os participantes acima.</div>');
    const phaseIndex=phases.indexOf(activity.status);document.querySelectorAll('.journey-steps li').forEach(item=>{const index=phases.indexOf(item.dataset.phase);item.classList.toggle('current',index===phaseIndex);item.classList.toggle('done',index<phaseIndex);});
    show('prepare-button',activity.status==='lobby');show('start-form',editable);show('extend-form',activity.status==='running');show('finish-button',activity.status==='running');show('finish-note',activity.status==='finished');show('start-readiness',editable);
    const readyTeams=teams.filter(team=>team.document?.ready&&teamReady(team)).length;const allReady=teams.length>=2&&readyTeams===teams.length;
    setText('start-readiness',teams.length<2?'Crie pelo menos 2 times para iniciar.':`${readyTeams}/${teams.length} times prontos: PDF enviado, todas as funções escolhidas, ao menos um atacante e um defensor.${activity.status==='lobby'?' Libere a preparação antes de iniciar.':''}`);$('start-readiness').className=`readiness ${allReady?'good':'warning'}`;
    renderEvents('teacher-events',events);renderTeamMetrics();renderEffectControls();
  }
  function renderStudent() {
    const {activity,viewer,teams=[],participants=[],events=[]}=state.snapshot;const team=teams.find(item=>item.id===viewer.teamId);show('student-waiting',!team);show('student-team-area',Boolean(team));const me=participants.find(participant=>participant.id===viewer.participantId);setText('student-identity',`${me?.name||'Participante'} · sua sessão está salva neste navegador.`);if(!team)return;
    setText('my-team-name',team.name);setText('my-score',team.score||0);setText('my-captures',team.captureCount||0);setText('my-defenses',team.defenseCount||0);setText('my-leaks',team.leakCount||0);setText('my-vault',team.compromised?'!':'◈');setText('my-vault-label',team.compromised?'CAPTURADO':team.document?.ready?'PROTEGIDO':'SEM PDF');$('my-vault').parentElement.classList.toggle('compromised',Boolean(team.compromised));
    setHtml('my-team-members',teamMembers(team).map(member=>`<span class="member-pill ${member.id===viewer.participantId?'mine':''}">${escape(member.name)}${member.id===viewer.participantId?' (você)':''}<span class="member-role">${escape(roles[member.role]||'ESCOLHA A FUNÇÃO')}</span></span>`).join(''));
    show('role-panel',['lobby','preparing'].includes(activity.status));document.querySelectorAll('[data-role]').forEach(button=>{const selected=button.dataset.role===viewer.role;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));});const ready=teamReady(team);setText('role-readiness',ready?'✓ Todas as funções escolhidas, com atacante e defensor. Vocês podem ajustar as funções até o início.':'Todos precisam escolher uma função, incluindo ao menos um atacante e um defensor.');$('role-readiness').className=`readiness ${ready?'good':'warning'}`;
    show('preparation-banner',activity.status==='preparing');show('live-student-arena',activity.status==='running');show('attack-panel',viewer.role==='attack');show('defense-panel',viewer.role==='defense');$('live-student-arena').classList.add('single');
    renderEvents('student-events',events,'Acompanhe aqui os acontecimentos da sua equipe.');renderAttack();renderDefense();
  }
  function updateOptions(id,options,empty) {
    const select=$(id);const previous=select.value;const html=`<option value="">${escape(empty)}</option>`+options.map(option=>`<option value="${escape(option.value)}" ${option.disabled?'disabled':''}>${escape(option.label)}</option>`).join('');
    if(state.renderCache.get(id)!==html){select.innerHTML=html;state.renderCache.set(id,html);if(options.some(option=>option.value===previous&&!option.disabled))select.value=previous;else {const firstAvailable=options.find(option=>!option.disabled);select.value=firstAvailable?.value||'';}}
  }
  function ownAttackIncident() {const viewer=state.snapshot?.viewer;const target=$('attack-target').value;return (state.snapshot?.incidents||[]).filter(incident=>incident.attackerId===viewer?.participantId&&incident.defenderTeamId===target&&incident.status!=='abandoned').sort((a,b)=>timeValue(b.lastActionAt)-timeValue(a.lastActionAt))[0];}
  function ownDefenseIncidents() {return (state.snapshot?.incidents||[]).filter(incident=>incident.defenderTeamId===state.snapshot.viewer.teamId&&incident.status!=='abandoned').sort((a,b)=>timeValue(b.lastActionAt)-timeValue(a.lastActionAt));}
  function renderAttack() {
    const {viewer,teams=[],captures=[],incidents=[]}=state.snapshot;const ongoing=incidents.find(incident=>incident.attackerId===viewer.participantId&&['active','blocked'].includes(incident.status));updateOptions('attack-target',teams.filter(team=>team.id!==viewer.teamId).map(team=>{const captured=captures.some(capture=>capture.attackerTeamId===viewer.teamId&&capture.defenderTeamId===team.id);return {value:team.id,label:`${team.name}${captured?' · já capturado':''}`,disabled:captured||Boolean(ongoing&&ongoing.defenderTeamId!==team.id)};}),'Selecione um alvo');if(ongoing)$('attack-target').value=ongoing.defenderTeamId;show('switch-target',Boolean(ongoing));const incident=ownAttackIncident();const stage=incident?.stage||0;const captured=incident?.status==='captured'||captures.some(capture=>capture.attackerTeamId===viewer.teamId&&capture.defenderTeamId===$('attack-target').value);
    const path=['Reconhecer','Inspecionar','Acessar','Extrair'].map((label,index)=>`<div class="path-step ${captured||stage>index?'done':stage===index?'active':''}">${index+1}. ${label}</div>`).join('');
    const caption=!$('attack-target').value?'Nenhum novo alvo disponível para captura.':captured?'✓ Documento já capturado por sua equipe. Escolha outro alvo.':!incident?'Execute scan para começar a investigação.':incident.status==='blocked'?'Conexão bloqueada. Execute reconnect e comece novamente.':`${stages[stage]||'Conexão aberta'} · IP virtual ${incident.route} · próximo: ${['scan','inspect','access','extract'][stage]}. Você pode encerrar esta conexão usando Trocar alvo.`;
    setHtml('attack-path',path+`<div class="path-caption">${escape(caption)}</div>`);
    /* No automatic command filling: the next step is a hint, not a repeated button. */
    setGuide('attack',state.attackCommand);updateToolButtons('attack');
  }
  function incidentHtml(incident,selected=false,clickable=true) {return `<${clickable?'button':'div'} ${clickable?'type="button"':''} class="incident-row ${selected?'selected':''}" ${clickable?`data-incident="${escape(incident.id)}"`:''}><span class="incident-detail"><strong>${escape(incident.attackerTeamName)} · ${escape(incident.attackerName)}</strong><small>${escape(stages[incident.stage]||stages[0])} · IP virtual ${escape(incident.route)} · ${Number(incident.defenseCount)||0} respostas</small></span><span class="incident-status ${escape(incident.status)}">${incident.status==='captured'?'CAPTUROU':incident.status==='blocked'?'BLOQUEADO':incident.responded?'RESPONDIDO':'ATIVO'}</span></${clickable?'button':'div'}>`;}
  function renderDefense() {
    const incidents=ownDefenseIncidents();updateOptions('defense-incident',incidents.map(incident=>({value:incident.id,label:`${incident.attackerTeamName} · ${incident.attackerName} · ${incident.status==='active'?stages[incident.stage]:incident.status==='blocked'?'bloqueado':'capturou'}`})),'Selecione uma conexão');
    setHtml('defense-connections',incidents.length?incidents.map(incident=>incidentHtml(incident,incident.id===$('defense-incident').value)).join(''):'<div class="empty-state">Nenhum atacante conectado ao seu cofre.</div>');
    setGuide('defense',state.defenseCommand);updateToolButtons('defense');
  }
  function setGuide(kind,command) {const tool=toolById[command];if(!tool)return;setText(`${kind}-guide-title`,`${tool.name} / ${command}`);setText(`${kind}-guide`,tool.hint);}
  function fillCommand(kind,command,focus=true) {state[`${kind}Command`]=command;$(`${kind}-command`).value=command;setGuide(kind,command);updateToolButtons(kind);state.entryMode[kind]='guided';if(focus)$(`${kind}-command`).focus();}
  function updateToolButtons(kind) {const used=state.snapshot?.viewer.commandGuard?.guidedUsed||[];document.querySelectorAll(`#${kind}-tools [data-command]`).forEach(button=>{const spent=used.includes(button.dataset.command);button.classList.toggle('selected',button.dataset.command===state[`${kind}Command`]);button.classList.toggle('used',spent);button.disabled=spent||state.busy;button.title=spent?'Você já usou o clique deste comando. Agora digite.':'Preencher uma única vez por jogador';button.setAttribute('aria-label',`${button.dataset.command}${spent?' · clique usado; digite o comando':' · preencher uma vez'}`);});}
  function commandStatus(kind,wait) {if(!state.snapshot)return '';if(cooldown(state.snapshot.viewer.commandGuard?.lockedUntil))return `Proteção contra autoclique · aguarde ${wait}s e digite novamente.`;return wait?`Intervalo entre comandos: ${wait}s.`:state.entryMode[kind]==='guided'?'Primeiro uso guiado. Clique em Executar.':state.entryMode[kind]==='typed'?'Comando digitado. Escreva exatamente como aparece no catálogo.':'Digite um comando ou use um botão que ainda não foi utilizado. Colagem desabilitada.';}
  function clearCommand(kind){$(`${kind}-command`).value='';state[`${kind}Command`]='';state.entryMode[kind]=null;updateToolButtons(kind);updateEnabled();}
  function commandInput(kind){const input=$(`${kind}-command`);input.addEventListener('input',()=>{state[`${kind}Command`]=parseCommand(input.value);state.entryMode[kind]=input.value.trim()?'typed':null;setGuide(kind,state[`${kind}Command`]);updateEnabled();});const block=event=>{event.preventDefault();notify('Nesta etapa, escreva o comando sem colar.',true);};input.addEventListener('paste',block);input.addEventListener('drop',block);input.addEventListener('beforeinput',event=>{if(/insertFromPaste|insertFromDrop/.test(event.inputType))block(event);});}

  function updateClock() {
    if(!state.snapshot)return;const {activity}=state.snapshot;const running=activity.status==='running';setText('clock-label',running?'TEMPO RESTANTE':activity.status==='finished'?'OPERAÇÃO ENCERRADA':'AGUARDANDO INÍCIO');
    if(running){const remaining=Math.max(0,timeValue(activity.endsAt)-(Date.now()+state.serverOffset));const seconds=Math.ceil(remaining/1000);setText('clock',`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`);document.querySelector('.operation-clock').classList.toggle('urgent',remaining<=60000);setText('clock-footnote',remaining===0?'Aguardando confirmação do servidor':'O professor pode adicionar tempo');}
    else{setText('clock',activity.status==='finished'?'00:00':'--:--');document.querySelector('.operation-clock').classList.remove('urgent');setText('clock-footnote',activity.status==='finished'?'Ranking final disponível':'O professor controla o tempo');}renderEffect();updateEnabled();
  }
  function cooldown(until) {return Math.max(0,Math.ceil((timeValue(until)-Date.now()-state.serverOffset)/1000));}
  function setFormDisabled(id,disabled) {const form=$(id);if(form)form.querySelectorAll('input,textarea,button').forEach(element=>element.disabled=disabled);}
  function updateEnabled() {
    if(!state.snapshot)return;const {activity,viewer,teams=[]}=state.snapshot;const editable=['lobby','preparing'].includes(activity.status);const running=activity.status==='running';const busy=state.busy;const startReady=activity.status==='preparing'&&teams.length>=2&&teams.every(team=>team.document?.ready&&teamReady(team));
    if(viewer.kind==='teacher'){renderEffectControls();setFormDisabled('team-form',!editable||busy);$('team-form').querySelector('button').disabled=!editable||busy||state.selectedMembers.size<2||state.selectedMembers.size>3||teams.length>=20;$('prepare-button').disabled=busy;$('start-form').querySelector('button').disabled=busy||!startReady;$('duration').disabled=busy||!editable;setFormDisabled('extend-form',busy||!running);setFormDisabled('announce-form',busy||activity.status==='finished');$('finish-button').disabled=busy;document.querySelectorAll('[data-upload],[data-delete-team]').forEach(element=>element.disabled=busy||!editable);}
    document.querySelectorAll('[data-role]').forEach(button=>button.disabled=busy||!editable);
    const attackIncident=ownAttackIncident();const attackWait=cooldown(Math.max(timeValue(attackIncident?.attackCooldownUntil),timeValue(viewer.attackCooldownUntil),timeValue(viewer.commandGuard?.cooldownUntil),timeValue(viewer.commandGuard?.lockedUntil)));const targetCaptured=(state.snapshot.captures||[]).some(capture=>capture.attackerTeamId===viewer.teamId&&capture.defenderTeamId===$('attack-target').value);const attackDisabled=busy||!running||viewer.role!=='attack'||!$('attack-target').value||attackWait>0||targetCaptured||!state.entryMode.attack;
    $('attack-command').disabled=busy||!running;$('attack-command-form').querySelector('button').disabled=attackDisabled;setTextButton('attack-command-form',attackWait?`Aguarde ${attackWait}s`:busy?'Executando…':'Executar ↵');$('attack-target').disabled=busy||!running||viewer.role!=='attack';$('switch-target').disabled=busy||!running||viewer.role!=='attack';
    const reserve=teams.find(team=>team.id===viewer.teamId)?.defenseReserve;const now=Date.now()+state.serverOffset;const recharge=activity.rules?.defenseRechargeMs||8000;const recovered=reserve?.nextChargeAt&&now>=reserve.nextChargeAt?1+Math.floor((now-reserve.nextChargeAt)/recharge):0;const charges=reserve?Math.min(reserve.capacity,reserve.charges+recovered):0;const chargeWait=reserve?.nextChargeAt?cooldown(reserve.nextChargeAt+recovered*recharge):0;setText('defense-reserve',reserve?`Reserva do time: ${charges}/${reserve.capacity} defesas${charges<reserve.capacity?` · +1 em ${chargeWait}s`:''}. Compartilhada entre os defensores.`:'');
    const defenseIncident=(state.snapshot.incidents||[]).find(incident=>incident.id===$('defense-incident').value);const defenseWait=cooldown(Math.max(state.defenseCommand==='logs'?0:timeValue(defenseIncident?.defenseCooldownUntil),timeValue(viewer.commandGuard?.cooldownUntil),timeValue(viewer.commandGuard?.lockedUntil)));const needsIncident=state.defenseCommand!=='logs';const invalidIncident=needsIncident&&(!defenseIncident||defenseIncident.status!=='active'||defenseIncident.stage<1||defenseIncident.responded);const noCharge=needsIncident&&charges===0;const defenseDisabled=busy||!running||viewer.role!=='defense'||invalidIncident||defenseWait>0||noCharge||!state.entryMode.defense;
    $('defense-command').disabled=busy||!running;$('defense-command-form').querySelector('button').disabled=defenseDisabled;setTextButton('defense-command-form',defenseWait?`Aguarde ${defenseWait}s`:noCharge?`Recarga ${chargeWait}s`:busy?'Executando…':'Executar ↵');$('defense-incident').disabled=busy||!running||viewer.role!=='defense';
    updateToolButtons('attack');updateToolButtons('defense');setText('attack-guard-status',commandStatus('attack',attackWait));setText('defense-guard-status',commandStatus('defense',defenseWait));
    document.querySelectorAll('[data-tab="toolkit"]').forEach(button=>button.disabled=activity.status==='lobby'&&viewer.kind!=='teacher');document.querySelectorAll('[data-practice]').forEach(button=>button.disabled=activity.status==='lobby'&&viewer.kind!=='teacher');$('training-form').querySelector('button').disabled=activity.status==='lobby'&&viewer.kind!=='teacher';
  }
  function setTextButton(formId,text){const button=$(formId).querySelector('button');if(button.textContent!==text)button.textContent=text;}
  function parseCommand(value) {return value.trim();}
  function logsText() {const incidents=ownDefenseIncidents();if(!incidents.length)return 'Nenhuma conexão de ataque registrada contra seu time.';return incidents.map(incident=>`${incident.attackerTeamName} / ${incident.attackerName}: ${incident.status==='active'?stages[incident.stage]:incident.status==='blocked'?'bloqueado':'PDF capturado'}; IP virtual ${incident.route}; ${incident.defenseCount||0} defesas.`).join('\n');}
  function setupTools() {
    setHtml('toolkit-cards',tools.map(tool=>`<article class="tool-card ${tool.kind}"><div class="tool-kind"><span>${tool.kind==='attack'?'ATAQUE':'DEFESA'}</span><span>${tool.id==='extract'?'+50 PT':tool.kind==='defense'&&tool.id!=='logs'?'+5 PT':'GUIA'}</span></div><h3>${escape(tool.name)}</h3><p>${escape(tool.description)}</p><code>$ ${escape(tool.id)}</code><dl><dt>Quando usar</dt><dd>${escape(tool.hint)}</dd><dt>Resultado</dt><dd>${escape(tool.effect)}</dd><dt>Conceito de SO</dt><dd>${escape(tool.concept)}</dd><dt>Intervalo</dt><dd>${escape(tool.cooldown)}</dd></dl><button class="button ghost" data-practice="${tool.id}" type="button">Preparar no treino ↗</button></article>`).join(''));
    for(const kind of ['attack','defense'])setHtml(`${kind}-tools`,tools.filter(tool=>tool.kind===kind).map(tool=>`<button type="button" class="compact-tool" data-kind="${kind}" data-command="${tool.id}" title="${escape(tool.name)}"><code>${tool.id}</code></button>`).join(''));
    resetTraining();$('attack-command').value='';$('defense-command').value='';terminal('attack-output','Estação pronta. Escolha um alvo e comece com scan.','info');terminal('defense-output','Estação pronta. Consulte logs ou selecione uma conexão.','info');
  }
  function renderTraining() {setHtml('training-state',`<span>${state.training.status==='captured'?'PDF recuperado':state.training.status==='blocked'?'Conexão bloqueada':escape(stages[state.training.stage])}</span><span>IP virtual 10.0.0.${state.training.route}</span>`);}
  function resetTraining() {state.training={stage:0,status:'active',route:1};$('training-output').textContent='';terminal('training-output','Treino iniciado. Time fictício: Kernel Azul. Comece com scan.','info');renderTraining();}
  function practice(command) {
    const training=state.training;terminal('training-output',`$ ${command}`,'command');let result='';let error=false;
    if(!toolById[command]){result='Comando desconhecido. Escolha uma ferramenta no catálogo acima.';error=true;}
    else if(command==='logs')result=`Kernel Azul: ${training.status}; ${stages[training.stage]}; IP virtual 10.0.0.${training.route}. Consulta sem pontuação.`;
    else if(command==='reconnect'){if(training.status!=='blocked'){result='A conexão não está bloqueada. Use scan para começar.';error=true;}else{training.status='active';training.stage=0;result='Conexão restabelecida. Comece novamente com scan.';}}
    else if(training.status==='captured'){result='O documento já foi capturado. Reinicie o treino para tentar outra estratégia.';error=true;}
    else if(training.status==='blocked'){result='Conexão bloqueada. Execute reconnect para continuar.';error=true;}
    else if(command==='scan'){if(training.stage!==0){result='Alvo já reconhecido. Continue com inspect.';error=true;}else{training.stage=1;result='Cofre encontrado no IP virtual. Serviço de documentos localizado. Próximo comando: inspect.';}}
    else if(command==='inspect'){if(training.stage!==1){result='Primeiro reconheça o alvo com scan.';error=true;}else{training.stage=2;result='Pista encontrada: uma permissão preparada permite abrir a sessão. Próximo comando: access.';}}
    else if(command==='access'){if(training.stage!==2){result='Encontre a pista com inspect antes de obter acesso.';error=true;}else{training.stage=3;result='Acesso obtido ao cofre. Extraia com extract. Um defensor agora pode executar revoke.';}}
    else if(command==='extract'){if(training.stage!==3){result='Você precisa obter acesso com access antes de extrair.';error=true;}else{training.status='captured';result='PDF fictício recuperado! Na rodada, essa captura vale 50 pontos e inicia o download do documento real.';}}
    else if(command==='reroute'){if(training.stage!==1){result='Use reroute somente na etapa Alvo reconhecido, depois de scan.';error=true;}else{training.stage=0;training.route++;result='IP virtual alterado somente para esta conexão. O atacante precisa executar scan novamente. Na rodada: defesa válida +5 pontos e uma carga consumida.';}}
    else if(command==='block'){if(training.stage!==2){result='Use block somente na etapa Pista encontrada, depois de inspect.';error=true;}else{training.stage=0;training.status='blocked';result='A conexão escolhida foi bloqueada. As demais conexões não são afetadas. O atacante precisa usar reconnect.';}}
    else if(command==='revoke'){if(training.stage!==3){result='Só é possível revogar uma sessão quando o atacante tem Acesso obtido.';error=true;}else{training.stage=2;result='Acesso revogado para esta conexão. O atacante precisa obter acesso novamente. Na rodada: defesa válida +5 pontos e uma carga consumida.';}}
    terminal('training-output',result,error?'error':'');renderTraining();
  }
  async function uploadPdf(input) {
    const file=input.files?.[0];if(!file||state.busy)return;if(file.size>3*1024*1024){notify('Este PDF ultrapassa 3 MB. Envie uma versão menor.',true);input.value='';return;}if(!/\.pdf$/i.test(file.name)){notify('Selecione um arquivo PDF.',true);input.value='';return;}
    state.busy=true;updateEnabled();notify(`Enviando ${file.name}…`);
    try{const buffer=await file.arrayBuffer();const bytes=new Uint8Array(buffer);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const result=await request(apiPath(`/documents/${encodeURIComponent(input.dataset.upload)}`),{method:'POST',body:{name:file.name,base64:btoa(binary)}});applySnapshot(result.snapshot);notify(result.message||'PDF preparado. O cofre já está pronto.');}catch(error){notify(error.message,true);}finally{input.value='';state.busy=false;updateEnabled();}
  }
  async function copyText(value,message) {try{await navigator.clipboard.writeText(value);notify(message);}catch{const textarea=document.createElement('textarea');textarea.value=value;textarea.style.position='fixed';textarea.style.top='-1000px';document.body.append(textarea);textarea.select();const copied=document.execCommand('copy');textarea.remove();notify(copied?message:`Copie este texto: ${value}`,!copied);}}
  function attachEvents() {
    $('choose-teacher').addEventListener('click',()=>entryMode('teacher'));$('choose-student').addEventListener('click',()=>entryMode('student'));document.querySelectorAll('[data-entry-back]').forEach(button=>button.addEventListener('click',()=>entryMode(null)));
    $('join-code').addEventListener('input',updateSavedSession);
    $('join-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;if(button.disabled)return;button.disabled=true;const code=$('join-code').value.trim().toUpperCase();try{const result=await request(`/api/activities/${encodeURIComponent(code)}/join`,{method:'POST',auth:false,body:{name:$('join-name').value.trim()}});saveSession({...result,code:result.code||code});await enterSession(result.code||code,result.token,result.snapshot);}catch(error){notify(error.message,true);}finally{button.disabled=false;}});
    $('create-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;if(button.disabled)return;button.disabled=true;try{const result=await request('/api/activities',{method:'POST',auth:false,body:{title:$('activity-title').value.trim(),password:$('teacher-password').value,maxIncoming:2}});saveSession(result);$('teacher-password').value='';await enterSession(result.code,result.token,result.snapshot);}catch(error){notify(error.message,true);}finally{button.disabled=false;}});
    $('home-button').addEventListener('click',()=>{sessionGeneration++;clearTimeout(state.pollTimer);state.code='';state.snapshot=null;state.token='';state.lastServerAt=0;state.renderCache.clear();state.alertQueue=[];if($('player-alert').open)$('player-alert').close();document.body.dataset.effect='';show('effect-hud',false);show('effect-decoration',false);show('entry-view',true);show('arena-view',false);document.body.classList.remove('public-view');history.replaceState(null,'',location.pathname);try{$('join-code').value=localStorage.getItem('thor:lastActivity')||'';}catch{}updateSavedSession();updateTeacherSession();entryMode(null);});
    document.addEventListener('click',async event=>{const resume=event.target.closest('[data-resume]');if(resume){const code=resume.dataset.resume;const saved=localSession(code);try{await enterSession(code,saved.token);}catch(error){notify(error.message,true);}return;}const tab=event.target.closest('[data-tab]');if(tab){switchTab(tab.dataset.tab);return;}if(event.target.closest('[data-open-toolkit]')){switchTab('toolkit');return;}const role=event.target.closest('[data-role]');if(role){await mutate({type:'role',role:role.dataset.role});return;}const deletion=event.target.closest('[data-delete-team]');if(deletion){if(confirm('Desfazer este time e liberar seus integrantes?'))await mutate({type:'team-delete',teamId:deletion.dataset.deleteTeam});return;}const tool=event.target.closest('[data-command]');if(tool){if(tool.disabled)return;const result=await mutate({type:'command-guide',command:tool.dataset.command});if(result){fillCommand(tool.dataset.kind,tool.dataset.command);updateEnabled();}return;}const practiceTool=event.target.closest('[data-practice]');if(practiceTool){$('training-command').value=practiceTool.dataset.practice;$('training-command').focus();$('training-form').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});return;}const incident=event.target.closest('[data-incident]');if(incident){$('defense-incident').value=incident.dataset.incident;renderDefense();updateEnabled();}});
    $('participant-list').addEventListener('change',event=>{const input=event.target.closest('[data-member]');if(!input)return;if(input.checked){if(state.selectedMembers.size>=3){input.checked=false;notify('Cada time pode ter até 3 integrantes.',true);return;}state.selectedMembers.add(input.dataset.member);}else state.selectedMembers.delete(input.dataset.member);setText('selected-count',`(${state.selectedMembers.size})`);state.renderCache.delete('participant-list');updateEnabled();});
    $('team-form').addEventListener('submit',async event=>{event.preventDefault();const result=await mutate({type:'team-create',name:$('team-name').value.trim(),memberIds:[...state.selectedMembers]});if(result){state.selectedMembers.clear();$('team-name').value='';renderTeacher();updateEnabled();}});
    $('team-list').addEventListener('change',event=>{if(event.target.matches('[data-upload]'))uploadPdf(event.target);});
    $('prepare-button').addEventListener('click',()=>mutate({type:'prepare'}));
    $('start-form').addEventListener('submit',event=>{event.preventDefault();mutate({type:'start',minutes:Number($('duration').value)});});
    $('extend-form').addEventListener('submit',event=>{event.preventDefault();mutate({type:'extend',minutes:Number($('extend-minutes').value)});});
    $('announce-form').addEventListener('submit',async event=>{event.preventDefault();const result=await mutate({type:'announce',text:$('announcement').value.trim()});if(result)$('announcement').value='';});
    $('finish-button').addEventListener('click',()=>{if(confirm('Encerrar a atividade agora e calcular o ranking final?'))mutate({type:'finish'});});
    $('copy-code').addEventListener('click',()=>copyText(state.code,'Código da atividade copiado.'));
    $('copy-public').addEventListener('click',()=>copyText(publicUrl(),'Link público copiado.'));
    $('attack-target').addEventListener('change',()=>{clearCommand('attack');renderAttack();updateEnabled();});
    $('switch-target').addEventListener('click',async()=>{const previous=$('attack-target').value;const result=await mutate({type:'attack-abandon'},'attack-output');if(result){const other=[...$('attack-target').options].find(option=>option.value&&option.value!==previous&&!option.disabled);$('attack-target').value=other?.value||'';clearCommand('attack');renderAttack();updateEnabled();}});
    $('defense-incident').addEventListener('change',()=>{renderDefense();updateEnabled();});
    $('attack-command-form').addEventListener('submit',async event=>{event.preventDefault();if(event.submitter.disabled||state.busy)return;const command=parseCommand($('attack-command').value);if(!toolById[command]||toolById[command].kind!=='attack'){terminal('attack-output','Comando incorreto. Escreva exatamente: scan, inspect, access, extract ou reconnect.','error');return;}state.attackCommand=command;terminal('attack-output',`$ ${command} / alvo: ${$('attack-target').selectedOptions[0]?.textContent}`,'command');const result=await mutate({type:'attack',targetTeamId:$('attack-target').value,command,nonce:state.snapshot.viewer.commandGuard?.nonce,entryMode:state.entryMode.attack},'attack-output');if(result)clearCommand('attack');else {state.entryMode.attack=null;updateEnabled();}});
    commandInput('attack');commandInput('defense');
    $('defense-command-form').addEventListener('submit',async event=>{event.preventDefault();if(event.submitter.disabled||state.busy)return;const command=parseCommand($('defense-command').value);if(!toolById[command]||toolById[command].kind!=='defense'){terminal('defense-output','Comando incorreto. Escreva exatamente: logs, reroute, block ou revoke.','error');return;}state.defenseCommand=command;terminal('defense-output',`$ ${command}${command==='logs'?'':` / conexão: ${$('defense-incident').selectedOptions[0]?.textContent}`}`,'command');const result=await mutate(command==='logs'?{type:'logs',nonce:state.snapshot.viewer.commandGuard?.nonce,entryMode:state.entryMode.defense}:{type:'defense',incidentId:$('defense-incident').value,command,nonce:state.snapshot.viewer.commandGuard?.nonce,entryMode:state.entryMode.defense},'defense-output');if(result){if(command==='logs')terminal('defense-output',logsText());clearCommand('defense');}else {state.entryMode.defense=null;updateEnabled();}});
    $('dismiss-player-alert').addEventListener('click',dismissBroadcast);$('player-alert').addEventListener('cancel',event=>{event.preventDefault();dismissBroadcast();});$('reduce-effect').addEventListener('click',()=>{state.reducedEffects=true;try{localStorage.setItem('thor:reducedEffects','1');}catch{}renderEffect();});
    $('metrics-team').addEventListener('change',renderTeamMetrics);$('effect-team').addEventListener('change',renderEffectControls);$('effect-kind').addEventListener('change',renderEffectControls);$('effect-form').addEventListener('submit',event=>{event.preventDefault();mutate({type:'effect',teamId:$('effect-team').value,effectId:$('effect-kind').value,seconds:Number($('effect-seconds').value)});});$('clear-effect').addEventListener('click',()=>mutate({type:'effect-clear',teamId:$('effect-team').value}));document.addEventListener('click',event=>{const card=event.target.closest('[data-metrics]');if(card){$('metrics-team').value=card.dataset.metrics;renderTeamMetrics();$('metrics-team').scrollIntoView({block:'center',behavior:'auto'});}});
    $('training-form').addEventListener('submit',event=>{event.preventDefault();if(event.submitter.disabled)return;practice(parseCommand($('training-command').value));});$('reset-training').addEventListener('click',resetTraining);
    document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.code&&!state.polling){clearTimeout(state.pollTimer);poll();}});
  }
  async function initialize() {
    setupTools();attachEvents();setInterval(updateClock,250);const params=new URLSearchParams(location.search);const code=(params.get('activity')||'').toUpperCase();$('join-code').value=code;updateSavedSession();updateTeacherSession();
    const cleanUrl=new URL(location.href);cleanUrl.searchParams.delete('password');cleanUrl.searchParams.delete('title');history.replaceState(null,'',cleanUrl);
    try{const config=await request('/api/health',{auth:false});show('teacher-password-field',Boolean(config.teacherPasswordRequired));$('teacher-password').required=Boolean(config.teacherPasswordRequired);}catch{notify('Não foi possível conectar ao servidor. Atualize a página para tentar novamente.',true);}
    $('join-form').querySelector('button[type="submit"]').disabled=false;$('create-form').querySelector('button[type="submit"]').disabled=false;
    entryMode(code?'student':['teacher','student'].includes(params.get('mode'))?params.get('mode'):null);
    if(code && params.get('public')==='1'){try{await enterSession(code,'',null,true);}catch(error){notify(error.message,true);}}
    else if(code){const saved=localSession(code);if(saved?.token)try{await enterSession(code,saved.token);}catch(error){notify(error.message,true);}}
    else{try{$('join-code').value=localStorage.getItem('thor:lastActivity')||'';}catch{}updateSavedSession();}
  }
  initialize();
})();
